server:
  port: 8081
  address: localhost

spring:
  application:
    name: SerializableApp
  datasource:
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
  h2:
    console:
      enabled: true
      path: /h2
